#!/bin/bash

set +e

product_group=toxrelay
product_dir=toxrelay

udevadm control --reload-rules

need_reboot=

#
# Создание пользовательских групп
#
#--- Group 'toxrelay' ---
res=$(cat /etc/group | grep "$product_group")
if [ -z "$res" ]; then
    groupadd -f $product_group
    echo "The group $product_group is created"
fi

res=$(groups $SUDO_USER | grep "$product_group")
if [ -z "$res" ]; then
    usermod -aG $product_group $SUDO_USER
    need_reboot=yes
fi

#--- Group 'usbrelay' ---
res=$(cat /etc/group | grep 'usbrelay')
if [ -z "$res" ]; then
    groupadd -f usbrelay
    echo "The group usbrelay is created"
fi

res=$(groups $SUDO_USER | grep 'usbrelay')
if [ -z "$res" ]; then
    usermod -aG usbrelay $SUDO_USER
    need_reboot=yes
fi

if [ "$need_reboot" = "yes" ]; then
    echo "============================================== "
    echo "! The user '$SUDO_USER' added to group '$product_group'."
    echo "! The user '$SUDO_USER' added to group: 'usbrelay'. "
    echo "! Need relogin user and repeat installation.   "
    echo "============================================== "
    exit 1
fi

#
# Назначение прав на рабочие директории
#
chown -R root:$product_group  /etc/$product_dir
chmod -R ug=rwX,o=rX          /etc/$product_dir

chown -R root:$product_group  /var/opt/$product_dir
chmod -R ug=rwX,o=rX          /var/opt/$product_dir

#
# Регистрация systemd-сервиса
#
sed -e "s/%TARGET_USER%/$SUDO_USER/" \
   -i /etc/systemd/system/toxrelay.service

systemctl daemon-reload

systemctl enable toxrelay.service
systemctl start  toxrelay.service

exit 0
